/* NIST CSF 2.0 wording for the framework map. Generated by _gen/build-csf-meta.py. Do not edit by hand. */
window.TF_CSFMETA={
 "source": "https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf",
 "functions": [
  {
   "id": "GV",
   "name": "Govern",
   "description": "The organization's cybersecurity risk management strategy, expectations, and policy are established, communicated, and monitored",
   "categories": [
    "GV.OC",
    "GV.RM",
    "GV.RR",
    "GV.PO",
    "GV.OV",
    "GV.SC"
   ]
  },
  {
   "id": "ID",
   "name": "Identify",
   "description": "The organization's current cybersecurity risks are understood",
   "categories": [
    "ID.AM",
    "ID.RA",
    "ID.IM"
   ]
  },
  {
   "id": "PR",
   "name": "Protect",
   "description": "Safeguards to manage the organization's cybersecurity risks are used",
   "categories": [
    "PR.AA",
    "PR.AT",
    "PR.DS",
    "PR.PS",
    "PR.IR"
   ]
  },
  {
   "id": "DE",
   "name": "Detect",
   "description": "Possible cybersecurity attacks and compromises are found and analyzed",
   "categories": [
    "DE.CM",
    "DE.AE"
   ]
  },
  {
   "id": "RS",
   "name": "Respond",
   "description": "Actions regarding a detected cybersecurity incident are taken",
   "categories": [
    "RS.MA",
    "RS.AN",
    "RS.CO",
    "RS.MI"
   ]
  },
  {
   "id": "RC",
   "name": "Recover",
   "description": "Assets and operations affected by a cybersecurity incident are restored",
   "categories": [
    "RC.RP",
    "RC.CO"
   ]
  }
 ],
 "categories": {
  "GV.OC": {
   "short": "Organizational context",
   "nist": "Organizational Context",
   "description": "The circumstances (mission, stakeholder expectations, dependencies, and legal, regulatory, and contractual requirements) surrounding the organization's cybersecurity risk management decisions are understood",
   "outOfScope": false,
   "note": ""
  },
  "GV.RM": {
   "short": "Risk strategy",
   "nist": "Risk Management Strategy",
   "description": "The organization's priorities, constraints, risk tolerance and appetite statements, and assumptions are established, communicated, and used to support operational risk decisions",
   "outOfScope": false,
   "note": "No skill covers this yet."
  },
  "GV.RR": {
   "short": "Roles and authority",
   "nist": "Roles, Responsibilities, and Authorities",
   "description": "Cybersecurity roles, responsibilities, and authorities to foster accountability, performance assessment, and continuous improvement are established and communicated",
   "outOfScope": false,
   "note": ""
  },
  "GV.PO": {
   "short": "Policy",
   "nist": "Policy",
   "description": "Organizational cybersecurity policy is established, communicated, and enforced",
   "outOfScope": false,
   "note": ""
  },
  "GV.OV": {
   "short": "Oversight",
   "nist": "Oversight",
   "description": "Results of organization-wide cybersecurity risk management activities and performance are used to inform, improve, and adjust the risk management strategy",
   "outOfScope": false,
   "note": ""
  },
  "GV.SC": {
   "short": "Supply chain risk",
   "nist": "Cybersecurity Supply Chain Risk Management",
   "description": "Cyber supply chain risk management processes are identified, established, managed, monitored, and improved by organizational stakeholders",
   "outOfScope": false,
   "note": ""
  },
  "ID.AM": {
   "short": "Asset management",
   "nist": "Asset Management",
   "description": "Assets (e.g., data, hardware, software, systems, facilities, services, people) that enable the organization to achieve business purposes are identified and managed consistent with their relative importance to organizational objectives and the organization's risk strategy",
   "outOfScope": false,
   "note": ""
  },
  "ID.RA": {
   "short": "Risk assessment",
   "nist": "Risk Assessment",
   "description": "The cybersecurity risk to the organization, assets, and individuals is understood by the organization",
   "outOfScope": false,
   "note": ""
  },
  "ID.IM": {
   "short": "Improvement",
   "nist": "Improvement",
   "description": "Improvements to organizational cybersecurity risk management processes, procedures and activities are identified across all CSF Functions",
   "outOfScope": false,
   "note": ""
  },
  "PR.AA": {
   "short": "Identity and access",
   "nist": "Identity Management, Authentication, and Access Control",
   "description": "Access to physical and logical assets is limited to authorized users, services, and hardware and managed commensurate with the assessed risk of unauthorized access",
   "outOfScope": false,
   "note": ""
  },
  "PR.AT": {
   "short": "Awareness and training",
   "nist": "Awareness and Training",
   "description": "The organization's personnel are provided with cybersecurity awareness and training so that they can perform their cybersecurity-related tasks",
   "outOfScope": true,
   "note": "The fleet does not train or test people."
  },
  "PR.DS": {
   "short": "Data security",
   "nist": "Data Security",
   "description": "Data are managed consistent with the organization's risk strategy to protect the confidentiality, integrity, and availability of information",
   "outOfScope": false,
   "note": ""
  },
  "PR.PS": {
   "short": "Platform security",
   "nist": "Platform Security",
   "description": "The hardware, software (e.g., firmware, operating systems, applications), and services of physical and virtual platforms are managed consistent with the organization's risk strategy to protect their confidentiality, integrity, and availability",
   "outOfScope": false,
   "note": ""
  },
  "PR.IR": {
   "short": "Infrastructure resilience",
   "nist": "Technology Infrastructure Resilience",
   "description": "Security architectures are managed with the organization's risk strategy to protect asset confidentiality, integrity, and availability, and organizational resilience",
   "outOfScope": false,
   "note": ""
  },
  "DE.CM": {
   "short": "Continuous monitoring",
   "nist": "Continuous Monitoring",
   "description": "Assets are monitored to find anomalies, indicators of compromise, and other potentially adverse events",
   "outOfScope": false,
   "note": ""
  },
  "DE.AE": {
   "short": "Adverse event analysis",
   "nist": "Adverse Event Analysis",
   "description": "Anomalies, indicators of compromise, and other potentially adverse events are analyzed to characterize the events and detect cybersecurity incidents",
   "outOfScope": false,
   "note": ""
  },
  "RS.MA": {
   "short": "Incident management",
   "nist": "Incident Management",
   "description": "Responses to detected cybersecurity incidents are managed",
   "outOfScope": false,
   "note": ""
  },
  "RS.AN": {
   "short": "Incident analysis",
   "nist": "Incident Analysis",
   "description": "Investigations are conducted to ensure effective response and support forensics and recovery activities",
   "outOfScope": false,
   "note": ""
  },
  "RS.CO": {
   "short": "Incident reporting",
   "nist": "Incident Response Reporting and Communication",
   "description": "Response activities are coordinated with internal and external stakeholders as required by laws, regulations, or policies",
   "outOfScope": false,
   "note": ""
  },
  "RS.MI": {
   "short": "Incident mitigation",
   "nist": "Incident Mitigation",
   "description": "Activities are performed to prevent expansion of an event and mitigate its effects",
   "outOfScope": false,
   "note": ""
  },
  "RC.RP": {
   "short": "Recovery plan",
   "nist": "Incident Recovery Plan Execution",
   "description": "Restoration activities are performed to ensure operational availability of systems and services affected by cybersecurity incidents",
   "outOfScope": false,
   "note": ""
  },
  "RC.CO": {
   "short": "Recovery communication",
   "nist": "Incident Recovery Communication",
   "description": "Restoration activities are coordinated with internal and external parties",
   "outOfScope": false,
   "note": ""
  }
 }
};
